build-image:
	docker build -t python-spotify .

build-image-nc:
	docker build --no-cache -t python-spotify .

run-image:
	docker run -it python-spotify

run-shell:
	docker run -it --entrypoint "/bin/bash" python-spotify