version: '3'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/tasks
    volumes:
      - ./app:/app

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: